version: '3.4'
services:
  restudemy:
    image: raphasalomao/restdocker
    restart: always
    build: /Users/rapha/OneDrive/Documentos/Projetos/RestDocker/02 RestWithSpringBoot
    working_dir: /Users/rapha/OneDrive/Documentos/Projetos/RestDocker/02 RestWithSpringBoot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./02 RestWithSpringBoot:/Users/rapha/OneDrive/Documentos/Projetos/RestDocker/02 RestWithSpringBoot
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run